### ISSUE TITLE
Doesn't work on Lineage 19.1

### ISSUE THREAD

**Issue by sconim** [Xposed-Modules-Repo/fr.netstat.locationindicatorwhitelist#1]
It worked fine until I rebooted the second time - when the whitelisted apps started generating the status bar location notification again. I tried wiping cache /rebooting but it doesn't seem to have any effect. 

As a suggestion, please consider showing the whitelisted apps (which I see it more as a blacklist) on top of the list.

Samsung SM-G980F / Lineage 19.1
LSPosed.

**Comment by gilbsgilbs** [comment]
This module is untested on LineageOS 19.1, so that's only half surprising. Providing your SystemUI.apk and LSPosed logs on [a recent debug build](https://github.com/gilbsgilbs/LocationIndicatorWhitelist/suites/10425061817/artifacts/515380287) would be required in order to understand what's going on, although I cannot guarantee I'll look into it anytime soon. As you can imagine, it requires quite a lot of trial and errors, so without owning the device, it's even harder.

> As a suggestion, please consider showing the whitelisted apps (which I see it more as a blacklist) on top of the list.

Yeah, the UI is very "MVP" at the moment. Having a search feature and displaying the package names instead along with their ID would also helpful.

---

Would you mind opening two issues (one for the UI and one for lineage 19.1) in the upstream repo: https://github.com/gilbsgilbs/LocationIndicatorWhitelist/issues/new ? It'd make referencing issues in PRs easier. In the meantime, I'll try to make it clearer that bugs should be reported upstream and not in this metarepo.

**Comment by gilbsgilbs** [comment]
> As a suggestion, please consider showing the whitelisted apps (which I see it more as a blacklist) on top of the list.

This was implemented in v1.1 along with search and dark theme.

I'm going to close this issue because:
- it was not opened in the good repository (should have been opened [upstream](https://github.com/gilbsgilbs/LocationIndicatorWhitelist)).
- as stated in the README, I don't plan on adding support for android versions/devices I do not own. Feel free to dig into the source code to figure out the problem with lineage 19.1, I'll review and merge any PR that supports other configurations.
